# Generated by Django 3.2.18 on 2023-02-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('discription', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
